// <auto-generated />
using System;
using DatabaseLayer.ApplicationContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203031736_init_third")]
    partial class init_third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLayer.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminMaster");
                });

            modelBuilder.Entity("BusinessLayer.Model.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonorThrough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StaffId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("BusinessLayer.Model.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeStaffId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("BusinessLayer.Model.ExpensesMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpenseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<string>("PaidTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("OfficeStaffId");

                    b.ToTable("ExpensesMaster");
                });

            modelBuilder.Entity("BusinessLayer.Model.FinancialYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeStaffId");

                    b.ToTable("FinancialYears");
                });

            modelBuilder.Entity("BusinessLayer.Model.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BusinessLayer.Model.Mosque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Established_Hijri")
                        .HasColumnType("date");

                    b.Property<string>("MosqueImam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MosqueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Mosques");
                });

            modelBuilder.Entity("BusinessLayer.Model.OfficeStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OfficeStaffs");
                });

            modelBuilder.Entity("BusinessLayer.Model.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishedYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("docType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("docUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationMaster");
                });

            modelBuilder.Entity("BusinessLayer.Model.Properties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Measurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("OwnershipDate")
                        .HasColumnType("date");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("BusinessLayer.Model.PropertyRentAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<decimal>("Deposite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertiesId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("PropertyRentAgreements");
                });

            modelBuilder.Entity("BusinessLayer.Model.PurchaseMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BillDate")
                        .HasColumnType("date");

                    b.Property<int?>("BillNo")
                        .HasColumnType("int");

                    b.Property<string>("BillUpload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("GSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GSTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GSTPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GSTType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("PurchaseMasters");
                });

            modelBuilder.Entity("BusinessLayer.Model.PurchasePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaseMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PurchaseMasterId");

                    b.ToTable("PurchasePayments");
                });

            modelBuilder.Entity("BusinessLayer.Model.RentMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyRentAgreementId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("PropertyRentAgreementId");

                    b.ToTable("RentMasters");
                });

            modelBuilder.Entity("BusinessLayer.Model.SalaryMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("GeneratedDate")
                        .HasColumnType("date");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalaryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StaffId");

                    b.ToTable("SalaryMaster");
                });

            modelBuilder.Entity("BusinessLayer.Model.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdharNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MosqueId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillageTown")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("BusinessLayer.Model.WithdrawalSalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeStaffId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<decimal>("WithdrawalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearId");

                    b.HasIndex("OfficeStaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("WithdrawalSalaries");
                });

            modelBuilder.Entity("BusinessLayer.Model.Donation", b =>
                {
                    b.HasOne("BusinessLayer.Model.FinancialYear", "FinancialYear")
                        .WithMany("DonationFYear")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("DonationsOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Organization", "Organization")
                        .WithMany("EnrollDonationOrg")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Staff", "Staff")
                        .WithMany("DonationStaff")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialYear");

                    b.Navigation("OfficeStaff");

                    b.Navigation("Organization");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusinessLayer.Model.ExpenseCategory", b =>
                {
                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("ExpCategoriesOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeStaff");
                });

            modelBuilder.Entity("BusinessLayer.Model.ExpensesMaster", b =>
                {
                    b.HasOne("BusinessLayer.Model.ExpenseCategory", "ExpenseCategory")
                        .WithMany("ExpMasterCategory")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.FinancialYear", "FinancialYear")
                        .WithMany("ExpensesMasterFYear")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("ExpensesMasterOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("FinancialYear");

                    b.Navigation("OfficeStaff");
                });

            modelBuilder.Entity("BusinessLayer.Model.FinancialYear", b =>
                {
                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("FinancialYearOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeStaff");
                });

            modelBuilder.Entity("BusinessLayer.Model.Member", b =>
                {
                    b.HasOne("BusinessLayer.Model.Organization", "Organization")
                        .WithMany("EnrollOrgMember")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BusinessLayer.Model.Mosque", b =>
                {
                    b.HasOne("BusinessLayer.Model.Organization", "OrgMosque")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgMosque");
                });

            modelBuilder.Entity("BusinessLayer.Model.Properties", b =>
                {
                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("PropertiesOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Organization", "Organization")
                        .WithMany("EnrollPropertiesOrg")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeStaff");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BusinessLayer.Model.PropertyRentAgreement", b =>
                {
                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("PRAOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Properties", "Properties")
                        .WithMany("EnrollProPRA")
                        .HasForeignKey("PropertiesId");

                    b.Navigation("OfficeStaff");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("BusinessLayer.Model.PurchaseMaster", b =>
                {
                    b.HasOne("BusinessLayer.Model.FinancialYear", "FinancialYear")
                        .WithMany("PurchaseMasterFYear")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("PurchaseMasterOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Organization", "Organization")
                        .WithMany("EnrollPurchaseMasterOrg")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialYear");

                    b.Navigation("OfficeStaff");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BusinessLayer.Model.PurchasePayment", b =>
                {
                    b.HasOne("BusinessLayer.Model.FinancialYear", "FinancialYear")
                        .WithMany("PurchasePaymentFYear")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("PurchasePaymentOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Organization", "Organization")
                        .WithMany("EnrollPurchasePaymentOrg")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.PurchaseMaster", "PurchaseMaster")
                        .WithMany("PurPaymentMaster")
                        .HasForeignKey("PurchaseMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialYear");

                    b.Navigation("OfficeStaff");

                    b.Navigation("Organization");

                    b.Navigation("PurchaseMaster");
                });

            modelBuilder.Entity("BusinessLayer.Model.RentMaster", b =>
                {
                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("RentMasterOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.PropertyRentAgreement", "PRAgreement")
                        .WithMany("RentMasterPRA")
                        .HasForeignKey("PropertyRentAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeStaff");

                    b.Navigation("PRAgreement");
                });

            modelBuilder.Entity("BusinessLayer.Model.SalaryMaster", b =>
                {
                    b.HasOne("BusinessLayer.Model.FinancialYear", "FinancialYear")
                        .WithMany("SalaryMasterFYear")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("SalaryMasterOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Organization", "Organization")
                        .WithMany("EnrollSalaryMasterOrg")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Staff", "Staff")
                        .WithMany("SalaryMasterStaff")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialYear");

                    b.Navigation("OfficeStaff");

                    b.Navigation("Organization");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusinessLayer.Model.Staff", b =>
                {
                    b.HasOne("BusinessLayer.Model.Mosque", "Mosque")
                        .WithMany("EnrollStaffMosque")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("EnrollStaffOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Organization", "Organization")
                        .WithMany("EnrollStaffOrg")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mosque");

                    b.Navigation("OfficeStaff");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BusinessLayer.Model.WithdrawalSalary", b =>
                {
                    b.HasOne("BusinessLayer.Model.FinancialYear", "FinancialYear")
                        .WithMany("WithdrawalFYear")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.OfficeStaff", "OfficeStaff")
                        .WithMany("WithdrawalOff")
                        .HasForeignKey("OfficeStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Staff", "Staff")
                        .WithMany("WithdrawalStaff")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialYear");

                    b.Navigation("OfficeStaff");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusinessLayer.Model.ExpenseCategory", b =>
                {
                    b.Navigation("ExpMasterCategory");
                });

            modelBuilder.Entity("BusinessLayer.Model.FinancialYear", b =>
                {
                    b.Navigation("DonationFYear");

                    b.Navigation("ExpensesMasterFYear");

                    b.Navigation("PurchaseMasterFYear");

                    b.Navigation("PurchasePaymentFYear");

                    b.Navigation("SalaryMasterFYear");

                    b.Navigation("WithdrawalFYear");
                });

            modelBuilder.Entity("BusinessLayer.Model.Mosque", b =>
                {
                    b.Navigation("EnrollStaffMosque");
                });

            modelBuilder.Entity("BusinessLayer.Model.OfficeStaff", b =>
                {
                    b.Navigation("DonationsOff");

                    b.Navigation("EnrollStaffOff");

                    b.Navigation("ExpCategoriesOff");

                    b.Navigation("ExpensesMasterOff");

                    b.Navigation("FinancialYearOff");

                    b.Navigation("PRAOff");

                    b.Navigation("PropertiesOff");

                    b.Navigation("PurchaseMasterOff");

                    b.Navigation("PurchasePaymentOff");

                    b.Navigation("RentMasterOff");

                    b.Navigation("SalaryMasterOff");

                    b.Navigation("WithdrawalOff");
                });

            modelBuilder.Entity("BusinessLayer.Model.Organization", b =>
                {
                    b.Navigation("EnrollDonationOrg");

                    b.Navigation("EnrollOrgMember");

                    b.Navigation("EnrollPropertiesOrg");

                    b.Navigation("EnrollPurchaseMasterOrg");

                    b.Navigation("EnrollPurchasePaymentOrg");

                    b.Navigation("EnrollSalaryMasterOrg");

                    b.Navigation("EnrollStaffOrg");
                });

            modelBuilder.Entity("BusinessLayer.Model.Properties", b =>
                {
                    b.Navigation("EnrollProPRA");
                });

            modelBuilder.Entity("BusinessLayer.Model.PropertyRentAgreement", b =>
                {
                    b.Navigation("RentMasterPRA");
                });

            modelBuilder.Entity("BusinessLayer.Model.PurchaseMaster", b =>
                {
                    b.Navigation("PurPaymentMaster");
                });

            modelBuilder.Entity("BusinessLayer.Model.Staff", b =>
                {
                    b.Navigation("DonationStaff");

                    b.Navigation("SalaryMasterStaff");

                    b.Navigation("WithdrawalStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
